title: Guide to Bricklink
email: info@guidetobricklink.com
description: > # this means to ignore newlines until "baseurl:"
  The ultimate guide to bricklink
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown