title: Guide to Bricklink
email: info@guidetobricklink.com
description: > # this means to ignore newlines until "baseurl:"
  The Ultimate Guide to Bricklink
url: "http://guidetobricklink.com"
avatar: "https://pbs.twimg.com/profile_images/581562827980296192/X_qUxcuB.png"

# Build settings
markdown: kramdown

# Metadata
meta:
  twitter: studshq

# Defaults
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      is_page: true
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
      icon: article
