title: Guide to Bricklink
email: info@guidetobricklink.com
description: > # this means to ignore newlines until "baseurl:"
  The Ultimate Guide to Bricklink
url: "http://guidetobricklink.com"

# Build settings
markdown: kramdown